/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AWSLogin: typeof import('./components/AWS/Login.vue')['default']
    copy: typeof import('./components/Layout/Header copy.vue')['default']
    DirectiveRipple: typeof import('./components/Directive/Ripple.vue')['default']
    ElementAvatar: typeof import('./components/Element/Avatar.vue')['default']
    ElementButton: typeof import('./components/Element/Button.vue')['default']
    ElementCard: typeof import('./components/Element/Card.vue')['default']
    ElementCenterContainer: typeof import('./components/Element/CenterContainer.vue')['default']
    ElementFieldInput: typeof import('./components/Element/Field/Input.vue')['default']
    ElementFieldText: typeof import('./components/Element/Field/Text.vue')['default']
    ElementFieldWrapper: typeof import('./components/Element/Field/Wrapper.vue')['default']
    ElementForm: typeof import('./components/Element/Form.vue')['default']
    ElementIcon: typeof import('./components/Element/Icon.vue')['default']
    ElementInput: typeof import('./components/Element/Input.vue')['default']
    ElementList: typeof import('./components/Element/List.vue')['default']
    ElementListItem: typeof import('./components/Element/ListItem.vue')['default']
    ElementText: typeof import('./components/Element/Text.vue')['default']
    LayoutContainer: typeof import('./components/Layout/Container.vue')['default']
    LayoutContent: typeof import('./components/Layout/Content.vue')['default']
    LayoutElementButton: typeof import('./components/Layout/Element/Button.vue')['default']
    LayoutFooter: typeof import('./components/Layout/Footer.vue')['default']
    LayoutHeader: typeof import('./components/Layout/Header.vue')['default']
    LayoutNav: typeof import('./components/Layout/Nav.vue')['default']
    LayoutNavIcon: typeof import('./components/Layout/NavIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
